apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: notflix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        version: 1.0.0
    spec:
      containers:
        - name: gateway
          image: martontoth/notflix-gateway:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: gateway-config
          resources:
            limits:
              memory: 256Mi
