kind: Service
apiVersion: v1
metadata:
  name: postgres-auth-external
  namespace: notflix
spec:
  selector:
    app: postgres-auth
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort
