# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8888/api/login
Content-Type: application/json

{
  "username": "martontoth",
  "password": "vizilo24"
}

###

GET http://localhost:8888/api/profile
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXJ0b250b3RoIiwiYXV0aCI6WyJVU0VSIl0sImlkIjoxLCJpYXQiOjE1NTM0NTc2NDgsImV4cCI6MTU1MzQ3OTI0OH0.W8mdSivsvPdfFJaslETQm4FkbQP_GQgboAQPska6EDE

###

GET http://localhost:8888/api/profile
Accept: application/json

###
