spring:
  application:
    name: 'Gateway'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8070
zuul:
  routes:
    ContentService: 'cms/**'
    UserService: 'users/**'
  prefix: '/api'
  ignored-patterns: 'internal/**'
