spring:
  application:
    name: 'ConfigServer'
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: '/home/totlol/Egyetem/notflix-config'
server:
  port: 8888