server:
  servlet:
    context-path: "/api"
  port: 8082

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5433/auth"
    username: auth
    password: auth
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

jwt:
  secret: "shakalaka"
