spring:
  application:
    name: 'UserService'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: 'ConfigServer'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
