apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: notflix
  labels:
    app: postgres
data:
  POSTGRES_DB: metadata
  POSTGRES_USER: metadata
  POSTGRES_PASSWORD: metadata
