kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: notflix
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
