apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
  namespace: notflix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: martontoth/notflix-auth:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: auth-config
          resources:
            limits:
              memory: 256Mi
